name: Build and zip exe
description: Build the Windows executable and create a versioned ZIP archive.

outputs:
  version:
    description: The application version
    value: ${{ steps.build_zip.outputs.version }}
  zip_path:
    description: The path to the versioned ZIP archive
    value: ${{ steps.build_zip.outputs.zip_path }}

runs:
  using: composite
  steps:
    - name: Build & Zip exe
      id: build_zip
      shell: powershell
      run: |
        python build.py
        $version = python -c "from src import __version__; print(__version__)"
        $folderName = "d4lf"
        $zipName = "d4lf_v" + $version
        Compress-Archive -Path $folderName -DestinationPath "$zipName.zip"
        echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "zip_path=$zipName.zip" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
