from typing import Protocol


class WindowSpecLike(Protocol):
    process_name: str

    def match(self, hwnd: int, check_window_name: bool = True) -> bool: ...


class WindowBackend(Protocol):
    """Behavior shared by the Windows and no-op window backends."""

    def get_window_name_from_id(self, hwnd: int) -> str: ...

    def get_process_from_window_name(self, hwnd: int) -> str: ...

    def get_window_spec_id(self, window_spec: WindowSpecLike) -> int | None: ...

    def start_detecting_window(self, window_spec: WindowSpecLike) -> None: ...

    def detect_window(self, window_spec: WindowSpecLike) -> None: ...

    def find_and_set_window_position(self, window_spec: WindowSpecLike) -> None: ...

    def stop_detecting_window(self) -> None: ...

    def move_window_to_foreground(self, window_spec: WindowSpecLike) -> None: ...

    def is_window_foreground(self, window_spec: WindowSpecLike) -> bool: ...

    def is_self_foreground(self) -> bool: ...
