name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup env
        uses: ./.github/actions/setup_env
      - name: Build & Zip exe
        id: build_zip
        uses: ./.github/actions/build_zip
      - name: Upload zip artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: d4lf_v${{ steps.build_zip.outputs.version }}
          path: ${{ steps.build_zip.outputs.zip_path }}
